### ISSUE TITLE
EKS Cluster update nodes does not take effect

### ISSUE THREAD

**Issue by mibaboo** [rancher/terraform-provider-rancher2#577]
Hi

I have successfully provision and EKS cluster using the config below.

```
terraform {
  required_providers {
    rancher2 = {
      source  = "rancher/rancher2"
      version = "1.11.0"
    }
  }
}
provider "rancher2" {
  api_url   = "https://rancher.example"
  token_key = "token"
  insecure  = "true"
}


resource "rancher2_cluster" "mycluster" {
  name        = "mycluster"
  description = "my cluster rancher2 imported cluster"
  eks_config {
    access_key         = XXX
    secret_key         = XXX
    kubernetes_version = 1.16
    ami                = XXX
    desired_nodes      = 1
    maximum_nodes      = 1
    minimum_nodes      = 1
    instance_type      = XXX
    region             = XXX
    virtual_network    = XXX
    ebs_encryption     = "true"
    subnets            = ["XXX"]
    security_groups    = ["sg-XXX"]
    user_data          = file("files/userdata.sh")
  }

```

However When I change the desired_nodes, maximum_nodes and minimum_nodes to 2 I can see the cluster says updating and I see the following logs but it does not actully update the nodes to 2 and it stays at 1 node.

> 2021/02/08 09:06:35 [INFO] [amazonelasticcontainerservice] Starting update
> 2021/02/08 09:06:35 [INFO] [amazonelasticcontainerservice] Update complete for cluster [c-nzb7g]
> 2021/02/08 09:06:35 [INFO] [amazonelasticcontainerservice] Starting post-check
> 2021/02/08 09:06:35 [INFO] [amazonelasticcontainerservice] Generating service account token
> 2021/02/08 09:06:36 [INFO] kontainerdriver amazonelasticcontainerservice stopped
> 2021/02/08 09:06:41 [INFO] kontainerdriver amazonelasticcontainerservice listening on address 127.0.0.1:33453
> 2021/02/08 09:06:41 [INFO] kontainerdriver amazonelasticcontainerservice stopped
> 2021/02/08 09:06:41 [INFO] Provisioned cluster [c-nzb7g]

**Comment by rawmind0** [comment]
This issue should be addressed with PR https://github.com/rancher/terraform-provider-rancher2/pull/608, provider v1.13.0

Please, reopen issue if needed

**Comment by mibaboo** [comment]
@rawmind0  would the fix only apply to eks_config_v2 resource ? 

I am trying on the eks_config resource and it still not taking effect.

**Comment by rawmind0** [comment]
@mibaboo , yes the fix only apply to eks_config_v2 argument, that is the new Rancher driver to use eks clusters.
