### ISSUE TITLE
Rancher delete existing node_groups and logging_types config  EKS imported cluster 

### ISSUE THREAD

**Issue by abelnieva** [rancher/terraform-provider-rancher2#800]
I have created EKS cluster with terraform , then imported to rancher, but rancher change the config in imported clusters, i dont want to  have rancher killing all cluster nodes  

code 

resource "rancher2_cluster" "cluster" {
  name                      = lower(var.cluster_name)
  description               = "Terraform EKS cluster"
  enable_cluster_monitoring = var.enable_cluster_monitoring
  eks_config_v2 {
    cloud_credential_id = data.rancher2_cloud_credential.rancher2norcal.id
    name                = var.cluster_name
    region              = var.region
    **imported            = true**
  }
}

terraform plan 

      **~ eks_config_v2 {
            cloud_credential_id   = "cattle-global-data:cc-rgp2g"
            imported              = true
          ~ logging_types         = [
              - "api",
              - "audit",
              - "authenticator",
              - "controllerManager",
              - "scheduler",
            ]
            name                  = "cluster-ie-eks"
            private_access        = false
            public_access         = false
            public_access_sources = []
            region                = "us-west-2"
            secrets_encryption    = false
            security_groups       = []
            subnets               = []
            tags                  = {}

          ~ node_groups {
              ~ desired_size           = 1 -> 2
                disk_size              = 20
                gpu                    = false
              ~ instance_type          = "t2.large" -> "t3.medium"
                labels                 = {
                    "type" = "custom"
                }
              ~ max_size               = 12 -> 2
              ~ min_size               = 1 -> 2
                name                   = "test-spot"
                request_spot_instances = false
                resource_tags          = {}
                spot_instance_types    = []
                subnets                = [
                    "subnet-0466aa...36738",
                    "subnet-05440....a00",
                    "subnet-0e2d..6b6...3c",
                ]
                tags                   = {}
                version                = "1.21"
            }
          ~ node_groups {
              ~ desired_size           = 1 -> 2
                disk_size              = 20
                gpu                    = false
              ~ instance_type          = "t2.large" -> "t3.medium"
                labels                 = {
                    "type" = "primary-infra"
                }
              ~ max_size               = 10 -> 2
              ~ min_size               = 1 -> 2
                name                   = "us-west-2a"
                request_spot_instances = false
                resource_tags          = {}
                spot_instance_types    = []
                subnets                = [
                    "subnet-0466a...68bc36738",
                ]
                tags                   = {}
                version                = "1.21"
            }
          ~ node_groups {
              ~ desired_size           = 1 -> 2
                disk_size              = 20
                gpu                    = false
              ~ instance_type          = "t2.large" -> "t3.medium"
                labels                 = {
                    "type" = "primary-infra"
                }
              ~ max_size               = 10 -> 2
              ~ min_size               = 1 -> 2
                name                   = "us-west-2b"
                request_spot_instances = false
                resource_tags          = {}
                spot_instance_types    = []
                subnets                = [
                    "subnet-05440....54e19fa00",
                ]
                tags                   = {}
                version                = "1.21"
            }
          ~ node_groups {
              ~ desired_size           = 1 -> 2
                disk_size              = 20
                gpu                    = false
              ~ instance_type          = "t2.large" -> "t3.medium"
                labels                 = {
                    "type" = "primary-infra"
                }
              ~ max_size               = 10 -> 2
              ~ min_size               = 1 -> 2
                name                   = "us-west-2c"
                request_spot_instances = false
                resource_tags          = {}
                spot_instance_types    = []
                subnets                = [
                    "subnet-0e2d6266....ac6603c",
                ]
                tags                   = {}
                version                = "1.21"
            }
        }
    }**

Plan: 1 to add, 1 to change, 0 to destroy.

**Comment by abelnieva** [comment]
#648  seems to be related

**Comment by wrkode** [comment]
Currently having the same issue.
Importing a cluster with `private_access= true` and `public_access=false` results in an imported EKS cluster with deleted/destroyed NodeGroup.
Tried to import the cluster with `public_access=true` and `private_access=false` and this worked.
**Rancher Version 2.6.2**
**Import Code**

```
data "rancher2_cloud_credential" "aws_crd" {
  name = var.rancher2_cloud_credential
}
resource "rancher2_cluster" "cluster" {
  name        = length(var.cluster_display_name) != 0 ? var.cluster_display_name : var.cluster_name
  description = var.cluster_description
  eks_config_v2 {
    cloud_credential_id = data.rancher2_cloud_credential.aws_crd.id
    name                = var.cluster_name
    region              = var.cluster_region
    imported            = true
    public_access       = false
    private_access      = true
  }
}
```

**Comment by thedadams** [comment]
@wrkode I would be interested to know what the API Endpoint Access is on the cluster you are importing. You should be able to see that in AWS console by selecting the cluster in EKS and going to the "Network" tab. The information is listed under "API server endpoint access" in the lower right-hand side.

**Comment by rawmind0** [comment]
@wrkode to import an eks cluster, you shouldn't specify `public_access` nor `private_access` arguments at the resource definition. These values should be managed by eks console. Defining them here may overwrite them at eks, triggering nodeGroups recreation

**Comment by kalinon** [comment]
can confirm this issue. it was introduced after v1.13.0

**Comment by kalinon** [comment]
If there is no `node_group` defined for an imported cluster, it will overwrite existing nodes with default values, which scales the ASGs to 2.

**Comment by a-blender** [comment]
I believe the fix to https://github.com/rancher/rancher/issues/36128 fixes this issue. If no `node_group` is defined in terraform for an imported cluster, Rancher no longer removes existing node groups.

This has been solved in all KEv2 operators.

**Comment by juanpciceri** [comment]
Hi @annablender I'm still facing the same issue...
Rancher version:v2.5.8

**Comment by jia3apb** [comment]
I have the same issue, I've tried Rancher 2.6.2 and 2.6.4.

**Comment by gchait** [comment]
@annablender 
Hey, I think this happened to me not only with node groups, but also with arbitrary changes to the cluster's endpoint access and logging, with `EndpointAccessUpdate` and `LoggingUpdate`, while not specified in the resource.
As of the latest provider and Rancher versions, does this still happen?

Generally, I think everyone who imports clusters doesn't expect them to be changed in any way.
And this behavior works perfectly from the Rancher GUI.

Thanks.

**Comment by a-blender** [comment]
Hello all,

This issue https://github.com/rancher/rancher/issues/36128 was fixed on rancher `v2.6.4` and up. It was not back ported into rancher v2.5. @juanpciceri If you could try upgrading rancher, this may solve your issue. @jia3apb Are you still seeing this problem as well when provisioning with Terraform? 

@gchait Noted. It should not, but if you are still seeing the same issue I can dev-validate it is not still happening on rancher 2.7. Which rancher instance are you using?
